quarkus.http.port=7070
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/demo
%prod.quarkus.datasource.username=quarkus
%prod.quarkus.datasource.password=quarkus
